site_name: "j3dog: A Secure, Scalable 3D Data Storage Solution"
site_description: "The j3dog database is a secure, scalable data storage solution that provides fast and reliable access to large amounts of data. With a focus on security, performance, and scalability, j3dog is well-suited for a wide range of applications and use cases."
site_author: Heusala Group
site_url: https://j3.dog
copyright: Copyright 2021-2023 <a href="https://heusalagroup.fi">Heusala Group</a>. All rights reserved.
repo_url: https://github.com/heusalagroup/j3.dog
edit_uri: edit/main/src
site_dir: ../webroot
docs_dir: src
remote_branch: main
theme:
  name: readthedocs
plugins:
- search:
    min_search_length: 2
    indexing: 'full'
- mermaid2
extra_css: [extra.css]
markdown_extensions:
- meta
- attr_list
- pymdownx.tabbed
- toc:
    permalink: true
    slugify: !!python/name:pymdownx.slugs.uslugify
- pymdownx.superfences:
    # make exceptions to highlighting of code:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:mermaid2.fence_mermaid
nav:
- "Introduction": index.md
- "Example Spreadsheet": examples.md
- "Support": support.md
