name: Run tests and publish release

on:
  push:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-latest, macos-latest]
        node-version: [14, 16, 18]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd testing && npm ci
    - run: cd testing && npm run test:ci
  list-changes:
    runs-on: ubuntu-latest
    needs:
    - test
    steps:
    - name: List changes
      uses: marketplace/actions/list-changes-action@v2
      with:
        from: ${{ steps.get-last-release.outputs.tag }}
        to: ${{ github.ref }}
        include_pull_requests: true
        include_issues: true
        output: changes.md
    - name: Get last release
      id: get-last-release
      uses: actions/get-previous-release@v1
  release:
    runs-on: ubuntu-latest
    needs:
      - list-changes
    steps:
      - name: Create release and tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.1.${{ github.run_number }}
          release_name: Release v0.1.${{ github.run_number }}
          body: |
            This release contains the following changes:
            $(cat changes.md)
          draft: false
          prerelease: false
