name: Run tests and publish release

on:
  push:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-latest, macos-latest]
        node-version: [14, 16, 18]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: git submodule update --init --recursive
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd testing && npm ci
    - run: cd testing && npm run test:ci
  release:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Create release and tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.1.${{ github.run_number }}
          release_name: Release v0.1.${{ github.run_number }}
          draft: false
          prerelease: false
